### ISSUE TITLE
Thanks agains (+ some issue)

### ISSUE THREAD

**Issue by ANaaim** [davidpagnon/Pose2Sim_Blender#1]
Great work :D Should ease some video verification. Thanks again for all this work super helpful.

Some problem i just encounter :
- When importing video and trc file from the same acqusition (the trc file is the one generated with P2S from the video) the video and the marker are not synchornised. Is there any additional stuff to do in blender to be able to have everything synchronise temporaly ? 

- Maybe the name of the camera when imported from a toml file should not be the number of the camera but its true name : 
For example for us it should be 26578 instead of cam_1 ==> it might be much easier to associate camera in blender.

```toml
[cam_1]
name = "26578"
size = [ 1088.0, 1920.0,]
matrix = [ [ 1677.425415046875, 0.0, 550.739013671875,], [ 0.0, 1677.491943359375, 959.772338875,], [ 0.0, 0.0, 1.0,],]
distortions = [ -0.000715875, 0.002123484375, 4.828125e-06, 7.15625e-06,]
rotation = [ -0.0801490876242585, 2.55670003636537, -1.7035997593979935,]
translation = [ -1.1008491007352483, 0.9451061357111141, 2.759258575604535,]
fisheye = false

[cam_2]
name = "26579"
size = [ 1088.0, 1920.0,]
matrix = [ [ 1680.458740234375, 0.0, 545.0693359375,], [ 0.0, 1680.66064453125, 923.3432006875,], [ 0.0, 0.0, 1.0,],]
distortions = [ -0.000690171875, 0.00212715625, 1.7359375e-05, -6.96875e-06,]
rotation = [ 1.651872305424128, -1.3123573659257894, 0.8062765511334361,]
translation = [ 0.40351437570705406, -0.18787945794784702, 4.89854989774333,]
fisheye = false
```
